# Generated by Django 3.2.7 on 2021-11-02 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='discription',
            new_name='description',
        ),
    ]
