# Generated by Django 3.2.7 on 2021-11-02 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_alter_game_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Games',
        ),
    ]
