# Generated by Django 3.2.7 on 2021-11-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0012_alter_games_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='gry',
            field=models.ManyToManyField(related_name='_Game_games_gry_+', to='Game.Games'),
        ),
    ]
