# Generated by Django 3.2.7 on 2021-11-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0014_alter_games_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='gry',
            field=models.ManyToManyField(to='Game.Games'),
        ),
    ]
