# Generated by Django 3.2.7 on 2021-11-02 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0015_alter_games_gry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='gry',
        ),
    ]
