# Generated by Django 3.2.7 on 2021-11-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0017_auto_20211102_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='games',
            name='category',
        ),
        migrations.AddField(
            model_name='games',
            name='category',
            field=models.ManyToManyField(to='Game.Category'),
        ),
    ]
