# Generated by Django 3.2.7 on 2021-11-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0019_auto_20211103_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='image',
            field=models.ImageField(default='none', upload_to='images/'),
            preserve_default=False,
        ),
    ]
