# Generated by Django 3.2.7 on 2021-11-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0021_alter_games_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, to='Game.Category'),
        ),
    ]
