# Generated by Django 3.2.7 on 2021-11-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0022_alter_games_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12),
        ),
    ]
